import { Header } from "@components/layout";
import "../styles/globals.css";

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactElement;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
